### ISSUE TITLE
PhantomJS fails tests which pass on firefox

### ISSUE THREAD

**Issue by jamiecollinson** [xolvio/meteor-cucumber#161]
I'm fully prepared for this to be nothing to do with `meteor-cucumber` and instead a problem with phantomjs, but I'm consistently getting cases of tests failing with phantomjs which pass with firefox. I don't have a runnable example pulled out, but here's some sample code where the `expect(text).to.contain('test tag')` will work on firefox but `text` will always be undefined on phantomjs:

(the logging in and navigation steps are defined elsewhere)

```
Feature: Company tags

  As a user of the app
  I want to be able to tag companies
  So that I can find companies I'm interested in easily

  Background:
    Given I am a logged in user
    And a company has been created
    And the company has a tag

  @dev
  Scenario: A user can see tags which have been added to a company
    When I navigate to "/companies"
    Then I should see a tag on the company
```

```
module.exports = function() {

  var url = require('url');

  this.Given(/^a company has been created$/, function(callback) {
    this.server.call('createCompany').then(callback);
  });

  this.Given(/^the company has a tag$/, function(callback) {
    this.server.call('addTagToCompany').then(callback);
  });

  this.Then(/^I should see a tag on the company$/, function(callback) {
    this.client
      // .waitForExist('#loading-page', 5000, true)
      // .waitForExist('#company-list')
      .getText('#company-list', function(err, text) {
        expect(text).to.contain('test tag');
      })
      .call(callback);
  });

};
```

I'm not sure what I should be doing to debug this, but wanted to see if anyone else is sharing similar issues? It doesn't seem to matter whether I use the commented out `waitForExist` statements or not.

Should I just drop the idea of using phantomjs? Are there some known set of conditions to avoid? Is it related to the version (I know there was recently a big phantomjs update but not sure if it's in `meteor-cucumber` yet).

**Comment by samhatoum** [comment]
I recently removed phantomjs as the default browser for exactly the reasons you're having issues with.

You can get it working, it's just a little more involved. Sometimes you have to patch phantomjs's lack of support for certain things, like the URL object for example that is used in FlowRouter.

The way to debug is quite involved. You need to run VELOCITY_DEBUG=1 and monitor the output of phantom for errors. The other thing you can do is take lots of screenshots to "see" what's happening. You can also start a phantomjs in webdriver mode directly in debug mode and get meteor cucumber to use that instance instead by providing a selenium host + port.

Let me also tell you that the reason phantom was selected in the first place was so that it can be run on CI servers. With CircleCI and Codeship having real browsers on them, phantom seems like a pain that's not really needed. Also when working locally it's better to really see what's happening, than to take screenshots and "see". So I would go back to the question: why use phantom?

**Comment by jamiecollinson** [comment]
I'm pretty sold on Firefox (or chrome) webdriver, but I guess the argument
for phantomjs is the "neater" setup without an external dependency, and
perhaps speed? I'd trade them for reliability and easy to write tests
though.

Switching to Firefox I saw about a 40% bump in time taken for circleci to
run our test suite. Maybe that's mostly startup time or not representative
in general.

As you say it's great that ci providers are supporting Firefox and chrome
drivers. For circleci switching was as simple as adding an environment
variable.

I guess you've answered my question - I was really looking for some
community guidance on what's working for other people. Much appreciated
(and love the book BTW).

**Comment by samhatoum** [comment]
no worries and thanks! Check our this config for chrome caching on circleci. 
https://github.com/xolvio/Letterpress/blob/master/circle.yml
