### ISSUE TITLE
Tests are not running

### ISSUE THREAD

**Issue by npvn** [xolvio/meteor-cucumber#34]
I'm unable to run sample cucumber tests. The app is running normally, but the velocity overlay only shows 'Loading' indefinitely.

Detailed log: https://gist.github.com/anonymous/ea1bf2fdb9e3c81bf82d

Steps to reproduce the issue:
- `meteor create testApp`
- Add `xolvio:cucumber`
- Add sample cucumber tests via the velocity overlay

**Comment by romanzolotarev** [comment]
Phuc, can't reproduce it. Tried on OS X. It works.

**Comment by npvn** [comment]
Just tried this on a clean [Nitrous Meteor box](http://blog.nitrous.io/2014/10/28/meteor-template-on-nitrous-io.html) and got the same issue. Looks like it only affects Linux.

**Comment by drenfr01** [comment]
I have the same comment on Mac OS X. It hangs on the proxy-package-sync] No changes to package.js file required line....

I also have the mocha package installed with velocity

**Comment by samhatoum** [comment]
I think this is related to the phantom binary being different on non OSX systems. I'll be updating webdriver so that it a) times out when such errors happen and b) it should allow the user to specify their phantomjs binary. 

I'm surprised @drenfr01 that you're on OSX and have this issue. Is this the case with blank project? Can you post your .versions file please?

**Comment by drenfr01** [comment]
I'm sorry @samhatoum, I definitely meant to put this in an issue opened for nblazer:meteor-casperjs. I guess I had too many tabs open....

**Comment by drenfr01** [comment]
Hi @samhatoum, 

Disregard my previous comment. I did encounter an error, but it's a little different than the one above. When I installed the mike:mocha on a clean project first, then meteor-cucumber, the cucumber tests hung indefinitely with the aforementioned "loading" in the velocity html-reporter.

Now, I tried installed meteor-cucumber first, then mike:mocha and the mocha tests are hanging indefinitely. I tried it with VELOCITY_DEGUG = 1 and didn't see any glaring errors. As requested, here are my packages (updated as of today):

amplify@1.0.0
application-configuration@1.0.4
autopublish@1.0.2
autoupdate@1.1.5
base64@1.0.2
binary-heap@1.0.2
blaze@2.0.4
blaze-tools@1.0.2
boilerplate-generator@1.0.2
callback-hook@1.0.2
check@1.0.4
coffeescript@1.0.5
ddp@1.0.14
deps@1.0.6
ejson@1.0.5
fastclick@1.0.2
follower-livedata@1.0.3
geojson-utils@1.0.2
html-tools@1.0.3
htmljs@1.0.3
http@1.0.10
id-map@1.0.2
insecure@1.0.2
jquery@1.11.3
json@1.0.2
launch-screen@1.0.1
less@1.0.12
livedata@1.0.12
logging@1.0.6
meteor@1.1.4
meteor-platform@1.2.1
mike:mocha@0.5.1
minifiers@1.1.3
minimongo@1.0.6
mobile-status-bar@1.0.2
mongo@1.0.11
observe-sequence@1.0.4
ordered-dict@1.0.2
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
random@1.0.2
reactive-dict@1.0.5
reactive-var@1.0.4
reload@1.1.2
retry@1.0.2
routepolicy@1.0.4
session@1.0.5
spacebars@1.0.5
spacebars-compiler@1.0.4
templating@1.0.11
tracker@1.0.5
ui@1.0.5
underscore@1.0.2
url@1.0.3
velocity:core@0.4.5
velocity:html-reporter@0.4.1
velocity:node-soft-mirror@0.2.8
velocity:shim@0.1.0
velocity:test-proxy@0.0.4
webapp@1.1.6
webapp-hashing@1.0.2
xolvio:cucumber@0.3.6
xolvio:webdriver@0.1.8

**Comment by npvn** [comment]
Thanks @samhatoum. Just let me know if you need any more information.

**Comment by samhatoum** [comment]
I think this is related to:
https://github.com/xolvio/meteor-webdriver/issues/18

**Comment by gibex** [comment]
Same here (loading...), clean project on OSX 10.10.2

amplify@1.0.0
application-configuration@1.0.4
autopublish@1.0.2
autoupdate@1.1.5
base64@1.0.2
binary-heap@1.0.2
blaze@2.0.4
blaze-tools@1.0.2
boilerplate-generator@1.0.2
callback-hook@1.0.2
check@1.0.4
coffeescript@1.0.5
ddp@1.0.14
deps@1.0.6
ejson@1.0.5
fastclick@1.0.2
follower-livedata@1.0.3
geojson-utils@1.0.2
html-tools@1.0.3
htmljs@1.0.3
http@1.0.10
id-map@1.0.2
insecure@1.0.2
jquery@1.11.3
json@1.0.2
launch-screen@1.0.1
less@1.0.12
livedata@1.0.12
logging@1.0.6
meteor@1.1.4
meteor-platform@1.2.1
minifiers@1.1.3
minimongo@1.0.6
mobile-status-bar@1.0.2
mongo@1.0.11
observe-sequence@1.0.4
ordered-dict@1.0.2
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
random@1.0.2
reactive-dict@1.0.5
reactive-var@1.0.4
reload@1.1.2
retry@1.0.2
routepolicy@1.0.4
session@1.0.5
spacebars@1.0.5
spacebars-compiler@1.0.4
templating@1.0.11
tracker@1.0.5
ui@1.0.5
underscore@1.0.2
url@1.0.3
velocity:core@0.4.5
velocity:html-reporter@0.4.1
velocity:node-soft-mirror@0.2.8
velocity:shim@0.1.0
velocity:test-proxy@0.0.4
webapp@1.1.6
webapp-hashing@1.0.2
xolvio:cucumber@0.3.8
xolvio:webdriver@0.1.8

DEBUG LOG: 

stream error Network error: ws://localhost:3000/websocket: connect ECONNREFUSED
[[[[[ ~/Sites/Meteor_projects/velocity-hell ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
I20150218-19:57:46.464(2)? [velocity] adding velocity core
I20150218-19:57:46.466(2)? [velocity] Not adding mirror-registrar because NODE_ENV is development and IS_MIRROR is false
I20150218-19:57:46.466(2)? [node-soft-mirror] adding server code
I20150218-19:57:46.466(2)? [velocity] Velocity not started. Queueing func
I20150218-19:57:46.743(2)? [velocity] Server startup
I20150218-19:57:46.743(2)? [velocity] app dir /Users/gad/Sites/Meteor_projects/velocity-hell
I20150218-19:57:46.744(2)? [velocity] config = {
I20150218-19:57:46.744(2)?   "cucumber": {
I20150218-19:57:46.744(2)?     "regex": "cucumber/.+\\.(feature|js|coffee|litcoffee|coffee\\.md)$",
I20150218-19:57:46.744(2)?     "name": "cucumber",
I20150218-19:57:46.744(2)?     "_regexp": {}
I20150218-19:57:46.744(2)?   }
I20150218-19:57:46.744(2)? }
I20150218-19:57:46.745(2)? [velocity] resetting the world
I20150218-19:57:46.745(2)? [velocity] frameworks with disable auto reset: []
I20150218-19:57:46.757(2)? [velocity-node-mirror] Server restarted.
I20150218-19:57:46.758(2)? [velocity-node-mirror] Aggressively restarting all mirrors
I20150218-19:57:46.770(2)? [node-soft-mirror]: LongRunningChildProcess.constructor(taskName=cucumber)
I20150218-19:57:46.770(2)? [node-soft-mirror]: LongRunningChildProcess.readPid()
I20150218-19:57:46.771(2)? [node-soft-mirror]: LongRunningChildProcess.readPid returns 37637
I20150218-19:57:46.771(2)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns true
I20150218-19:57:46.771(2)? [node-soft-mirror] Restarting Mirror for framework cucumber
I20150218-19:57:46.771(2)? [node-soft-mirror]: LongRunningChildProcess.kill(signal=SIGINT)
I20150218-19:57:46.773(2)? [velocity] Mirror requested { framework: 'cucumber',
I20150218-19:57:46.773(2)?   port: 5000,
I20150218-19:57:46.773(2)?   rootUrlPath: '',
I20150218-19:57:46.773(2)?   host: 'http://localhost:5000/',
I20150218-19:57:46.774(2)?   rootUrl: 'http://localhost:5000/' }
I20150218-19:57:46.774(2)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns false
I20150218-19:57:46.775(2)? [node-soft-mirror]: LongRunningChildProcess.spawn() { command: '/Users/gad/.meteor/packages/meteor-tool/.1.0.40.1ytdwaf++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/bin/node',
I20150218-19:57:46.775(2)?   args: [ '/Users/gad/Sites/Meteor_projects/velocity-hell/.meteor/local/build/main.js' ],
I20150218-19:57:46.775(2)?   options: 
I20150218-19:57:46.775(2)?    { detached: true,
I20150218-19:57:46.776(2)?      cwd: '/Users/gad/Sites/Meteor_projects/velocity-hell',
I20150218-19:57:46.776(2)?      env: 
I20150218-19:57:46.776(2)?       { PORT: 5000,
I20150218-19:57:46.776(2)?         HOST: 'http://localhost:5000/',
I20150218-19:57:46.776(2)?         ROOT_URL_PATH: '',
I20150218-19:57:46.776(2)?         ROOT_URL: 'http://localhost:5000/',
I20150218-19:57:46.776(2)?         FRAMEWORK: 'cucumber',
I20150218-19:57:46.777(2)?         MONGO_URL: 'mongodb://127.0.0.1:3001/cucumber',
I20150218-19:57:46.777(2)?         PARENT_URL: 'http://localhost:3000/',
I20150218-19:57:46.777(2)?         IS_MIRROR: true,
I20150218-19:57:46.777(2)?         METEOR_SETTINGS: '{}',
I20150218-19:57:46.777(2)?         TERM_PROGRAM: 'Apple_Terminal',
I20150218-19:57:46.777(2)?         TERM: 'xterm-256color',
I20150218-19:57:46.777(2)?         SHELL: '/bin/bash',
I20150218-19:57:46.777(2)?         TMPDIR: '/var/folders/t9/qgp8j5w95jn_6rqd_pg2wb8c0000gn/T/',
I20150218-19:57:46.778(2)?         Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.PGuPjIBDF7/Render',
I20150218-19:57:46.778(2)?         TERM_PROGRAM_VERSION: '343.6',
I20150218-19:57:46.778(2)?         OLDPWD: '/Users/gad/.meteor/packages/meteor-tool/1.0.40/meteor-tool-os.osx.x86_64',
I20150218-19:57:46.778(2)?         TERM_SESSION_ID: 'C011D9C6-F6EC-4F9D-9289-D91F6E3E7963',
I20150218-19:57:46.778(2)?         USER: 'gad',
I20150218-19:57:46.778(2)?         SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.z0f0RUuwho/Listeners',
I20150218-19:57:46.778(2)?         __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',
I20150218-19:57:46.779(2)?         PATH: '/opt/local/bin:/opt/local/sbin:/opt/local/libexec/perl5.12/sitebin/:/usr/lib/php/bin:/usr/lib/php/pear/bin/pear:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/ImageMagick/bin',
I20150218-19:57:46.779(2)?         LC_COLLATE: 'en_US.UTF-8',
I20150218-19:57:46.779(2)?         PWD: '/Users/gad/Sites/Meteor_projects/velocity-hell',
I20150218-19:57:46.779(2)?         XPC_FLAGS: '0x0',
I20150218-19:57:46.779(2)?         MY_DEV_NAME: 'local',
I20150218-19:57:46.779(2)?         XPC_SERVICE_NAME: '0',
I20150218-19:57:46.779(2)?         HOME: '/Users/gad',
I20150218-19:57:46.779(2)?         SHLVL: '1',
I20150218-19:57:46.779(2)?         VELOCITY_DEBUG: '1',
I20150218-19:57:46.780(2)?         LOGNAME: 'gad',
I20150218-19:57:46.780(2)?         LC_CTYPE: 'UTF-8',
I20150218-19:57:46.780(2)?         MOBILE_DDP_URL: 'http://localhost:3000',
I20150218-19:57:46.780(2)?         MOBILE_ROOT_URL: 'http://localhost:3000',
I20150218-19:57:46.780(2)?         MONGO_OPLOG_URL: 'mongodb://127.0.0.1:3001/local',
I20150218-19:57:46.780(2)?         APP_ID: '1xher041t2lgrdo5nhed',
I20150218-19:57:46.780(2)?         NODE_ENV: 'development',
I20150218-19:57:46.781(2)?         HTTP_FORWARDED_COUNT: '1',
I20150218-19:57:46.781(2)?         ENABLE_METEOR_SHELL: 'true',
I20150218-19:57:46.781(2)?         METEOR_PARENT_PID: '37667',
I20150218-19:57:46.781(2)?         METEOR_PRINT_ON_LISTEN: 'true' } } }
I20150218-19:57:46.781(2)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns false
I20150218-19:57:46.781(2)? [node-soft-mirror]: /Users/gad/Sites/Meteor_projects/velocity-hell/.meteor/local/build/programs/server/assets/packages/velocity_node-soft-mirror/lib/spawnScript.js
I20150218-19:57:46.781(2)? [node-soft-mirror]: The pid of the main Meteor app process is null
I20150218-19:57:46.782(2)? [node-soft-mirror]: LongRunningChildProcess.spawn is spawning 'node'
I20150218-19:57:46.782(2)? [node-soft-mirror]: LongRunningChildProcess._setPid(pid=37688)
I20150218-19:57:46.782(2)? [node-soft-mirror]: Saving cucumber pid 37688 to /Users/gad/Sites/Meteor_projects/velocity-hell/.meteor/local/run/cucumber.pid
I20150218-19:57:46.782(2)? [velocity-node-mirror] Mirror process forked with pid 37688
I20150218-19:57:46.789(2)? [node-soft-mirror] Aggressively reload client
I20150218-19:57:46.790(2)? [velocity] Mirror requested { framework: 'cucumber',
I20150218-19:57:46.790(2)?   port: 5000,
I20150218-19:57:46.790(2)?   rootUrlPath: '',
I20150218-19:57:46.790(2)?   host: 'http://localhost:5000/',
I20150218-19:57:46.790(2)?   rootUrl: 'http://localhost:5000/' }
I20150218-19:57:46.791(2)? [node-soft-mirror]: LongRunningChildProcess.isRunning returns true
=> Started your app.

=> App running at: http://localhost:3000/
I20150218-19:57:46.859(2)? [velocity] Target framework for tests/cucumber/features/sample.feature is cucumber
I20150218-19:57:46.872(2)? [velocity] Target framework for tests/cucumber/features/step_definitions/sampleSteps.js is cucumber
I20150218-19:57:46.873(2)? [velocity] Target framework for tests/cucumber/features/support/hooks.js is cucumber
I20150218-19:57:46.874(2)? [velocity] Target framework for tests/cucumber/features/support/world.js is cucumber
I20150218-19:57:46.876(2)? [velocity] File scan complete, now watching /tests
I20150218-19:57:46.876(2)? [velocity] Triggering queued startup functions
I20150218-19:57:46.882(2)? [proxy-package-sync] Test file added tests/cucumber/features/sample.feature
I20150218-19:57:46.883(2)? [proxy-package-sync] Test file added tests/cucumber/features/step_definitions/sampleSteps.js
I20150218-19:57:46.886(2)? [proxy-package-sync] Test file added tests/cucumber/features/support/hooks.js
I20150218-19:57:46.886(2)? [proxy-package-sync] Test file added tests/cucumber/features/support/world.js
I20150218-19:57:47.086(2)? [proxy-package-sync] Checking if a new package.js needs to be written because {} undefined
I20150218-19:57:47.086(2)? [proxy-package-sync] Generating in-memory package.js
I20150218-19:57:47.087(2)? [proxy-package-sync] Fixture files list length:  0
I20150218-19:57:47.088(2)? [proxy-package-sync] Test files list length:  4
I20150218-19:57:47.088(2)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/sample.feature
I20150218-19:57:47.088(2)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/step_definitions/sampleSteps.js
I20150218-19:57:47.089(2)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/support/hooks.js
I20150218-19:57:47.089(2)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/support/world.js
I20150218-19:57:47.089(2)? [proxy-package-sync] Comparing:
I20150218-19:57:47.090(2)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20150218-19:57:47.090(2)? [proxy-package-sync] - - - - - - - - - currentPackageJS: - - - - - - - - - - - - -
I20150218-19:57:47.090(2)? Package.describe({
I20150218-19:57:47.090(2)? 	name: "velocity:test-proxy",
I20150218-19:57:47.090(2)? 	summary: "Dynamically created package to expose test files to mirrors",
I20150218-19:57:47.090(2)? 	version: "0.0.4",
I20150218-19:57:47.090(2)? 	debugOnly: true
I20150218-19:57:47.090(2)? });
I20150218-19:57:47.090(2)? 
I20150218-19:57:47.090(2)? Package.on_use(function (api) {
I20150218-19:57:47.090(2)? 	api.use("coffeescript", ["client", "server"]);
I20150218-19:57:47.090(2)? });
I20150218-19:57:47.091(2)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20150218-19:57:47.091(2)? [proxy-package-sync] - - - - - - - - - generatedPackageJsContent - - - - - - - - -
I20150218-19:57:47.093(2)? Package.describe({
I20150218-19:57:47.093(2)? 	name: "velocity:test-proxy",
I20150218-19:57:47.093(2)? 	summary: "Dynamically created package to expose test files to mirrors",
I20150218-19:57:47.093(2)? 	version: "0.0.4",
I20150218-19:57:47.094(2)? 	debugOnly: true
I20150218-19:57:47.094(2)? });
I20150218-19:57:47.094(2)? 
I20150218-19:57:47.094(2)? Package.on_use(function (api) {
I20150218-19:57:47.094(2)? 	api.use("coffeescript", ["client", "server"]);
I20150218-19:57:47.095(2)? });
I20150218-19:57:47.095(2)? [proxy-package-sync] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I20150218-19:57:47.095(2)? [proxy-package-sync] No changes to package.js file required

**Comment by samhatoum** [comment]
can't see anything obvious. Is this on a fresh project + `meteor add xolvio:cucumber`?

Can you try to go to http://localhost:5000 and see if the mirror is working?

**Comment by gibex** [comment]
Yes, 

"It works!"

**Comment by samhatoum** [comment]
The new project worked or going to the mirror worked?

**Comment by gibex** [comment]
yes, to "fresh project + xolvio:cucumber"

"It works" is the message on localhost:5000

**Comment by samhatoum** [comment]
do you have any files under `/cucumber/features/`

**Comment by samhatoum** [comment]
@npvn Did you get this resolved? You should be able to fix this by adding an env var that says where to find phantom like this:

```
PHANTOM_PATH=`which phantomjs` meteor
```

**Comment by gibex** [comment]
yes, 2 folders and sample.feature.

On Tue, Feb 24, 2015 at 9:39 PM, Sam Hatoum <notifications@github.com>
wrote:

> do you have any files under /cucumber/features/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xolvio/meteor-cucumber/issues/34#issuecomment-75829578>
> .
>



-- 
Gabriel Doroftei
+40741055054
http://twitter.com/GabiDoroftei

**Comment by gibex** [comment]
All good for me, had that port opened by apache :) 

thanks

**Comment by stevenmathews** [comment]
@samhatoum Having the same problem (linux). New meteor project with xolvio:cucumber added. I create the sample tests but the button remains until I restart meteor. It is then stuck on loading.

Came here and installed phantomjs. When I run ```PHANTOM_PATH=`which phantomjs` meteor```, I get this error message [https://gist.github.com/stevenmathews/a067269cceee22c2a823](https://gist.github.com/stevenmathews/a067269cceee22c2a823)

 Running ```VELOCITY_DEBUG=1 meteor``` [https://gist.github.com/stevenmathews/d670c70355417a9a602d](https://gist.github.com/stevenmathews/d670c70355417a9a602d)

**Comment by samhatoum** [comment]
can you access localhost:5000 from your browser?

**Comment by alexoldenburg** [comment]
I'm having the same "loading" issue, but I don't have access to the localhost:5000... Could you help me on my way @samhatoum

**Comment by alexoldenburg** [comment]
@samhatoum I guess three times a charm, it's working now... what could have been the issue?

**Comment by stevenmathews** [comment]
@samhatoum Yes I have access to localhost:5000. Doesn't have the velocity sidepanel.

**Comment by samhatoum** [comment]
could you please try with an empty app (or the the [example app](https://github.com/meteor-velocity/velocity-examples/tree/master/leaderboard-cucumber)) and let me know if you see the same behavior.

**Comment by samhatoum** [comment]
@alexoldenburg really difficult to say :)

**Comment by stevenmathews** [comment]
@samhatoum  The error message above was for a empty app to work through your "Building Letterpress" chapter.

It was the error that I got after clicking the add sample tests button. I later read that the goal was to create everything manually which I started doing. 

I got to the "implement step definitions" section and just got "Cucumber is running" on the server and the "loading" velocity screen on the client. 

I tried adding the code to pass the test and got [this error](https://gist.github.com/stevenmathews/d8c17dd2479511370f06).

Running the [example](https://github.com/meteor-velocity/velocity-examples/tree/master/leaderboard-cucumber) works!

**Comment by ncrofts** [comment]
I also see the same problem i.e. running on linux, the leaderboard example runs ok, but no cucumber tests are being run.

The "loading" message just stays on screen in the velocity overlay and the tests don't run. The list of files does however update the Last Modified timestamp of the cucumber files when I change them.

The console indicates "Cucumber is running" but shows "0 scenarios and 0 steps"

Are there any suggestions on how to get this working? Thanks in advance.

**Comment by aurerua** [comment]
Hi, I am new to Meteor and after trying out most of the things in the Discover Meteor book, I am trying to get started with testing. 
I am running into the same problem as ncrofts above, though.
I would be very grateful one could help. Thanks.

**Comment by jimmiebtlr** [comment]
I'm also experiencing what seem's to be the same problem.  In my case, commenting out part of my fixtures file seem's to cause them to run again.  My logs seem to be showing the fixtures file as a test file, and not as a fixture file.

```
I20150326-03:35:47.936(-5)? [proxy-package-sync] Checking if a new package.js needs to be written because {} undefined
I20150326-03:35:47.936(-5)? [proxy-package-sync] Generating in-memory package.js
I20150326-03:35:47.937(-5)? [proxy-package-sync] Fixture files list length:  0
I20150326-03:35:47.938(-5)? [proxy-package-sync] Test files list length:  8
I20150326-03:35:47.938(-5)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/step_definitions/generalSteps.js
I20150326-03:35:47.938(-5)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/step_definitions/machines/machines.js
I20150326-03:35:47.938(-5)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/step_definitions/userSteps.js
I20150326-03:35:47.939(-5)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/step_definitions/workOrders/form_steps.js
I20150326-03:35:47.939(-5)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/support/hooks.js
I20150326-03:35:47.939(-5)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/support/world.js
I20150326-03:35:47.939(-5)? [proxy-package-sync] Test file will not be included in mirror tests/cucumber/features/workOrders.feature
I20150326-03:35:47.939(-5)? [proxy-package-sync] Test file will be included in mirror tests/cucumber/fixtures.js
```

**Comment by SVanhull** [comment]
I was following along the same path as the failures seen here. After getting the PhantomJS situation under control, the solution for me was getting xolvio:webdriver to update. 

The version installed as a dependancy was 0.3.1 and once I got it updated to 0.5.2 everything seemed ok. `meteor update` does not update the dependancy so I had to add the webdriver package directly first.

I just ran:
```
    meteor add xolvio:webdriver
    meteor update
```

Adding the webdriver package went very fast because 0.3.1 was already installed as a dependancy, meteor update goes a bit slower as it actually updates the package to 0.5.2. Then... running tests!

Maybe we just need an update to the dependancy versions in the package?

**Comment by bennett-elder** [comment]
I have an update on this. npvn and I could not run this on Nitrous.io because Chrome doesn't want to run headless without assistance. To get it working on my Nitrous box I actually had to install java, chromedriver, Xvfb, and export the DISPLAY environment variable as the same display number I used with Xvfb (export DISPLAY=:0). Other useful environment variables while troubleshooting: VELOCITY_DEBUG=1 for more detail and SELENIUM_BROWSER=firefox to temporarily remove the Chrome requirement. :) :+1:
