### ISSUE TITLE
Assertions are thrown as exceptions in Meteor.bindEnvironment

### ISSUE THREAD

**Issue by wackazong** [xolvio/meteor-cucumber#46]
Another thing: I cannot do assertions in a step where I use Meteor.bindEnvironment. Consider the following:
```
    this.Then('I should receive an email to confirm my email address', Meteor.bindEnvironment(function (callback) {
      var link = helper.world.connection.call('getEmailLink', helper.world.data.guest.email);
      assert(link != undefined);
      callback();
    }));
```
This throws an error instead of logging an assertion failure, and cucumber does not run again. It has nothing to do with the call itself, the same behaviour is showing when I comment it out. When I take out Meteor.bindEnvironment then assertions work fine. Problem is now, how do I check the return value of a method call, e.g. in this scenario?

**Comment by Sanjo** [comment]
Can you try to use Meteor.bindEnvironment at a higher level. It may work if Cucumber doesn't use something like setTimeout.

I currently don't know the internals of Cucumber, so I don't know if this is relevant. For Jasmine I ended up with patching Jasmine so it uses Meteor.setTimeout instead of the node.js setTimeout.

**Comment by Sanjo** [comment]
I just saw that in the latest version (0.3.10) you no longer need to do the Meteor.bindEnvironment yourself. The package will do this automatically.

**Comment by samhatoum** [comment]
Yep, no longer needed. closing
