### ISSUE TITLE
Calling steps within steps to keep things DRY

### ISSUE THREAD

**Issue by geekyme** [xolvio/meteor-cucumber#62]
I think the ruby implementation allows you to group steps by calling steps within other steps. I think this keeps things DRY and allow our cucumber tests to be more maintable. 

https://github.com/cucumber/cucumber/wiki/Calling-Steps-from-Step-Definitions

Is this currently possible in meteor-cucumber?

**Comment by hexsprite** [comment]
I looked at cucumberJS which this is built on to see if this was possible and I don't think so because of the way it's architected. You could ask on the mailing list for that project to be sure...






On Sunday, Mar 29, 2015 at 4:48 PM, Shawn Lim <notifications@github.com>, wrote:

I think the ruby implementation allows you to group steps by calling steps within other steps. I think this keeps things DRY and allow our cucumber tests to be more maintable. 


https://github.com/cucumber/cucumber/wiki/Calling-Steps-from-Step-Definitions


Is this currently possible in meteor-cucumber?

**Comment by queso** [comment]
No this isn't possible in the same way.

You basically have to move the shared code into it's own named function and then you can reuse that named function across other steps.

Cucumber.js itself said javascript had good enough facilities to do this kind of thing and they wouldn't implement it in Cucumber.js.

**Comment by queso** [comment]
See https://github.com/cucumber/cucumber-js/issues/11

**Comment by samhatoum** [comment]
Closing this due to no current solution
